### ISSUE TITLE
Where did the fav star go?

### ISSUE THREAD

**Issue by molarmanful** [vihanb/PPCG-Design#17]
I can't see the grey star below the upvote/downvote counter on any of the questions.

**Comment by ETHproductions** [comment]
Weird, I can still see it with the latest version. Did you make any changes to your version of the userscript?

**Comment by vihanb** [comment]
It's probably due to rawgit rate limiting with the SVG stuff. The SVG hosting site should probably be moved from github...

**Comment by molarmanful** [comment]
This has been strangely fixed... hmm...

**Comment by addisoncrump** [comment]
@molarmanful This is _still_ not fixed for me.

**Comment by vihanb** [comment]
Ugh, it must be rawgit, I'll try to fix it

**Comment by vihanb** [comment]
It _should_ be fixed now

**Comment by addisoncrump** [comment]
It is not fixed, continue discussion in the Nineteenth Byte.

**Comment by addisoncrump** [comment]
Safari simply doesn't load the images for the stars whatsoever. This is the image tree:

![screen shot 2016-01-25 at 4 17 15 am](https://cloud.githubusercontent.com/assets/10711159/12542389/929384e0-c31a-11e5-9300-e35ba6881ea9.png)

**Comment by addisoncrump** [comment]
However, when I go to that page, this loads:

![screen shot 2016-01-25 at 4 18 32 am](https://cloud.githubusercontent.com/assets/10711159/12542404/bc19eda4-c31a-11e5-91f6-f1cf2ad7c693.png)

**Comment by vihanb** [comment]
Has this been fixed?

**Comment by addisoncrump** [comment]
No. Problem is still there - I think that Safari just doesn't like svg generated images.

**Comment by vihanb** [comment]
Works for me on Safari 9.0.1... I could try to change the file name

**Comment by addisoncrump** [comment]
I'm running on Safari 8.0.7, currently.

**Comment by Mego** [comment]
Blame caching - this only seems to happen shortly after a new version of the userscript is pushed, and even then not always.

**Comment by vihanb** [comment]
I'll close this then I guess...
