### ISSUE TITLE
TryItOnline link has some problems

### ISSUE THREAD

**Issue by addisoncrump** [vihanb/PPCG-Design#40]
One: the link does not always automatically form the tryitonline output:

![screen shot 2016-02-09 at 6 09 41 pm](https://cloud.githubusercontent.com/assets/10711159/12926427/49700142-cf5b-11e5-9d6f-a62a4d3208c0.png)

Two: Try it online links seem to make the user script not load fully:

![screen shot 2016-02-09 at 6 31 55 pm](https://cloud.githubusercontent.com/assets/10711159/12926465/7068511e-cf5b-11e5-8901-a90590df414f.png)

**Comment by RikerW** [comment]
The userscript load thing happens a lot of places for me... Like every question older than about a year.

**Comment by ETHproductions** [comment]
I haven't seen either of these issues, but often it produces wrong output for me, namely Jelly and Retina (with the latter, newlines are always preceded by `Â`)

**Comment by vihanb** [comment]
That's weird. Does TryItOnline not use UTF-8?

**Comment by vihanb** [comment]
The loading bug is due to it erroring out. Are you running the latest version? I pushed a change would should prevent that

**Comment by addisoncrump** [comment]
Alright, that fixed the loading issue. But the TryItOnline link still doesn't always output:

![screen shot 2016-02-10 at 2 52 04 pm 1](https://cloud.githubusercontent.com/assets/10711159/12950599/e802e748-d005-11e5-832c-1451d1936c94.png)

**Comment by addisoncrump** [comment]
I don't think I've even seen it work on Safari 8.1.

![screen shot 2016-02-10 at 2 53 12 pm](https://cloud.githubusercontent.com/assets/10711159/12950642/13f1cdba-d006-11e5-9e48-11c85bf1dbc5.png)

![screen shot 2016-02-10 at 2 53 44 pm](https://cloud.githubusercontent.com/assets/10711159/12950665/2d847db8-d006-11e5-8ba7-14de8107d593.png)

**Comment by vihanb** [comment]
That is weird..., could you check the XHR response and values?

**Comment by addisoncrump** [comment]
I don't know how to do that. D: Also, the loading problem is back:

![screen shot 2016-02-11 at 8 46 14 am](https://cloud.githubusercontent.com/assets/10711159/12972309/fe5d4772-d09b-11e5-8cda-31d4f882d0e2.png)

Same question, on a link to my Vitsy answer. It may be a problem with my specific answer (it has no bytes involved and outputs a _lot_.

**Comment by vihanb** [comment]
Hopefully it's not different on Safari 8 but open up the console, Resources -> All Resources. Under "Stylesheets" there should be a folder named "XHRs", look for "backend". Or just check for any errors.

For the loading problem. I've figured that out, it's due to bad URL parsing :|

**Comment by vihanb** [comment]
That _should_ fix it, in terms of errors in the response. Those are _probably_ issues with TIO's response

**Comment by addisoncrump** [comment]
Is debug on by default?
